exp:
    fold : 3 
    epochs : 200
    patience : 3 
    num_workers : 0 
    lr : 0.005
    wd : 0.0
    lr_patience : 1 
    lr_factor : 0.4
    batch_size_1 : 32
    batch_size_2 : 16
    vertical_flip : 0.5
    horizontal_flip : 0.5
    output_size : 1
    csv_columns : ["laterality", "view", "age", "implant"]
